# Generated by Django 6.1 on 2026-08-25 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('lecture_note', 'Lecture Note'), ('slide', 'Slide'), ('video', 'Video'), ('document', 'Document'), ('link', 'External Link'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/materials/')),
                ('external_url', models.URLField(blank=True, help_text='URL for external resources')),
                ('week_number', models.PositiveIntegerField(blank=True, help_text='Week this material belongs to', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_materials_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField(help_text='Course objectives and learning outcomes')),
                ('prerequisites', models.TextField(blank=True, help_text='Required prior knowledge or courses')),
                ('textbooks', models.TextField(blank=True, help_text='Required and recommended textbooks')),
                ('grading_policy', models.TextField(blank=True, help_text='How grades are calculated')),
                ('course_policies', models.TextField(blank=True, help_text='Attendance, late work, academic integrity policies')),
                ('weekly_outline', models.TextField(blank=True, help_text='Week-by-week topic breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'syllabi',
            },
        ),
    ]
